### ISSUE TITLE
Help using Blabel

### ISSUE THREAD

**Issue by coolyear123** [Edinburgh-Genome-Foundry/blabel#13]
I've installed Blabel both with pip and by unzipping the source files but I still get an error in python when I try to do a test run. I don't know whats going on. Attached are the errors.

Traceback (most recent call last):
  File "C:\Users\DPetit\PycharmProjects\snakeLabels\main.py", line 5, in <module>
    from blabel import LabelWriter
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\blabel\__init__.py", line 5, in <module>
    from .blabel import LabelWriter
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\blabel\blabel.py", line 6, in <module>
    from weasyprint import HTML
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\weasyprint\__init__.py", line 322, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\weasyprint\css\__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\weasyprint\css\computed_values.py", line 16, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\weasyprint\text\ffi.py", line 380, in <module>
    gobject = _dlopen(
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\weasyprint\text\ffi.py", line 377, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\DPetit\PycharmProjects\AntScan\venv\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

Process finished with exit code 1

**Comment by Zulko** [comment]
Sorry to hear that. It looks like the failure happens during Weasyprint import. You should visit [their Github](https://github.com/Kozea/WeasyPrint/issues), you may find a solution there (please report back if you do! looks like a Windows/Weasyprint issue).

**Comment by mightyroy** [comment]
```
import os
# insert the GTK3 Runtime folder at the beginning
GTK_FOLDER = r'C:\Program Files\GTK3-Runtime Win64\bin'
os.environ['PATH'] = GTK_FOLDER + os.pathsep + os.environ.get('PATH', '')
from blabel import LabelWriter
```

Add the above before importing other libraries after installing GTK3 on windows. It worked for me.
