### ISSUE TITLE
blabel gives error with pyinstaller

### ISSUE THREAD

**Issue by AntoineBricard** [Edinburgh-Genome-Foundry/blabel#21]
Hi,
I'm developing a python script that print a sticker using blabel package. This script run under ubuntu 2022.
From the VSCode debug, I'm able to run the script and print stickers but when I try to make a single executable file using pyinstaller, launching the executable return the following error :
`Traceback (most recent call last):
  File "python_script.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "blabel/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "blabel/blabel.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "weasyprint/__init__.py", line 336, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "weasyprint/css/__init__.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "weasyprint/css/computed_values.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "weasyprint/text/line_break.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pyphen/__init__.py", line 33, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIRsPxXu/pyphen/dictionaries'
[55951] Failed to execute script 'python_script' due to unhandled exception!
`

But if I generate the executable without the import of blabel package inside the python_script.py, there is no error.
Is there a way to use pyinstaller and blabel without getting any error ?

Thanks in advance,
Antoine

**Comment by veghp** [comment]
Hi, unfortunately I'm not familiar with pyinstaller. This line `No such file or directory: '/tmp/_MEIRsPxXu/pyphen/dictionaries'` suggests that the issue is with pyinstaller or its installation / setup, so perhaps asking the authors would be a good way forward?

I had good experience using Docker for "packaging" dependencies, for example: https://github.com/Edinburgh-Genome-Foundry/EGF_Docker_Jupyter

**Comment by Zulko** [comment]
Also worth mentioning that the dependency `weasyprint` appears several times in the error and so it could be an issue between pyinstaller and Weasyprint. Maybe the Weasyprint community will have some insights?

**Comment by AntoineBricard** [comment]
Hi,
Thanks both for the reply, I will check with pyinstaller and weasyprint community.

Antoine
